export type MetaSearchAppDetailsItem = {
  application_id: string;
  name: string;
  created_at: Date;
  security_contact_emails: any[];
  log_region: string;
  custom_analytics_retention_days: number;
  completed_index_configuration_at: Date;
  selected_onboarding_type: null;
  owner: Owner;
  is_collaborator: boolean;
  current_number_team_members: number;
  production_indices: string[];
  relogin_required: boolean;
  search_api_key: string;
  write_api_key: string;
  admin_api_key: string;
  analytics_api_key: string;
  recommendation_api_key: string;
  usage_api_key: string;
  monitoring_api_key: string;
  offline_version: number;
  clusters: Cluster[];
  multicluster: boolean;
  replicas: Cluster[];
  cluster_hosts: string[];
  main_region: string;
  first_payment_date: Date;
  current_app_month: string;
  dns: DNS;
  chargeable: boolean;
  "has_pending_charge?": boolean;
  plan_can_be_changed: boolean;
  current_user_can_enable_ai_recommendation: boolean;
  has_ai_recommendation_beta: boolean;
  has_accepted_ai_recommendation_terms: boolean;
  plan: Plan;
  future_plan: null;
  block_overquota: boolean;
  can_choose_legacy_plan: boolean;
  first_day_of_plan: boolean;
  replicas_frozen: boolean;
  free: boolean;
  trial: boolean;
  trial_ends_on: Date;
  current_user_is_owner: boolean;
  has_multi_applications_setup: boolean;
  acls: string[];
  main_cluster_name: string;
  pending_api_keys_generation: boolean;
  accepted_personalization: Date;
  has_zendesk_crawlers: boolean;
  analytics_v2_access: boolean;
  enrolling_to_analytics: boolean;
  shopify: boolean;
  zuora_enabled: boolean;
  deletable: boolean;
  deleting_requires_feedback: boolean;
  last_insights_activity_on: null;
  readonly: boolean;
  application_type: string;
};

type Cluster = {
  name: string;
  hosts: string[];
  region: string;
  region_name: string;
};

type DNS = {
  should_be_propagated: boolean;
  propagated_first: boolean;
  propagated_second: boolean;
};

type Owner = {
  email: string;
  name: string;
  persona: null;
};

type Plan = {
  price_cents: number;
  price_yearly_cents: number;
  discount: number;
  currency: string;
  current_exchange_rate: number;
  name: string;
  label: string;
  version: number;
  renewal_date: Date;
  renewal_day: number;
  analytics_retention_days: number;
  analytics_dashboard: boolean;
  analytics_results: boolean;
  analytics_advanced: boolean;
  analytics_api: boolean;
  team_members: number;
  first_day_of_plan: boolean;
  remaining_days: number;
  current_billing_month_start_date: Date;
  days_since_start_of_plan_month: number;
  additional_operations_type: string;
  has_query_rules: boolean;
  has_click_analytics: boolean;
  allow_optional_filters_in_rules: boolean;
  included_rules: number;
  has_combined_usage_units: boolean;
  included_combined_usage_units: number;
  total_included_combined_usage_units: number;
  pay_as_you_go: boolean;
  has_indices_size_quota: boolean;
  dsn_formula: string;
  dsn_base_price_percent: null;
  dsn_upgradable: boolean;
  premium_sla: boolean;
  premium_sla_base_price_percent: null;
  premium_support: boolean;
  premium_support_base_price_percent: null;
  usage_api: boolean;
  monitoring_api: boolean;
  dedicated_infrastructure: boolean;
  used_search_capacity: boolean;
  commitment: number;
  self_serve: boolean;
  indexing: boolean;
  index_create: boolean;
  index_create_replica: boolean;
  index_copy: boolean;
  index_rename: boolean;
  index_onboarding: boolean;
  index_synonyms: boolean;
  records_add_manually: boolean;
  records_add_from_file: boolean;
  records_add_from_api: boolean;
  admin_api_key_display: boolean;
  rules_visual_editor: boolean;
  rules_manual_editor: boolean;
  record_size_thresholds: RecordSizeThresholds;
  rules_max_promoted_position: number;
  ab_testing: boolean;
  ai_recommendation: boolean;
  click_analytics: boolean;
  crawler: boolean;
  docsearch: boolean;
  dsn: boolean;
  dynamic_synonyms_suggestions: boolean;
  extension_support: boolean;
  nlu_enabled: boolean;
  personalization: boolean;
  query_suggestions: boolean;
  reranking: boolean;
  self_serve_sso: boolean;
  support_email: boolean;
  team: boolean;
  team_acls: boolean;
  usage_report: boolean;
  virtual_replica: boolean;
  included_records: number;
  total_included_records_history: TotalIncludedRecordsHistory[];
  included_operations: number;
  included_synonyms: number;
  included_max_qps: null;
  additional_records_unit: number;
  additional_records_unit_price_cents: number;
  additional_operations_unit: number;
  additional_operations_unit_price_cents: number;
  included_indices_size_gigabytes: number;
  free_plan_acknowledgement: boolean;
};

type RecordSizeThresholds = {
  healthy: number;
  large: number;
  max: number;
};

type TotalIncludedRecordsHistory = {
  t: number;
  v: number;
};
